theme: jekyll-theme-cayman
title: Cloud Prisma Margin Estimator (cPME)
description: Cloud Prisma Margin Estimator (cPME) calculates margin for an uploaded portfolio according to Eurex Prisma methodology
